services:
  # Frontend
  - type: web
    name: pedidos-front
    runtime: docker
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://pedidos-back.onrender.com/api # Replace with your actual backend URL after its first deploy
    dockerContext: .
