databases:
  - name: pedidosweb-db
    databaseName: pedidosweb
    plan: free

services:
  # Backend
  - type: web
    name: pedidos-back
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pedidosweb-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pedidosweb-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pedidosweb-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    dockerContext: Pedidos-back

  # Frontend
  - type: web
    name: pedidos-front
    runtime: docker
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://pedidos-back.onrender.com/api # Change this after your first deploy
    dockerContext: Pedidos-front
